# Generated by Django 3.2.6 on 2021-08-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bw_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, null=True, verbose_name='公司名称')),
                ('type', models.IntegerField(choices=[(-1, '黑'), (0, '白')], max_length=2)),
                ('status', models.IntegerField(choices=[(-1, '未审核'), (0, '已审核')], max_length=2)),
            ],
        ),
    ]
