# Generated by Django 3.2.6 on 2021-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw_list_search', '0002_auto_20210816_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bw_list',
            options={'verbose_name': '黑白名单', 'verbose_name_plural': '黑白名单'},
        ),
        migrations.AddField(
            model_name='bw_list',
            name='detail',
            field=models.CharField(default='', max_length=260, verbose_name='详细信息'),
        ),
    ]
