# Generated by Django 3.2.6 on 2021-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw_list_search', '0003_auto_20210816_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bw_list',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=260, verbose_name='详细信息'),
        ),
    ]
